### ISSUE TITLE
Why use prepublish as an external script?

### ISSUE THREAD

**Issue by lucasmotta** [juliancwirko/react-npm-boilerplate#1]
The script is only one line, so I don't really need to have one extra file just for that.
You could use directly on your `package.json` IMO:

``` json
{
   "prepublish": "babel --plugins 'transform-runtime' src --ignore __tests__ --out-dir ./dist"
}
```

**Comment by juliancwirko** [comment]
Yeah, maybe I should remove .sh file. Thanks for pointing it out.

**Comment by juliancwirko** [comment]
prepublish.sh removed
