### ISSUE TITLE
How to use the content of the package in my own package?

### ISSUE THREAD

**Issue by aymericbouzy** [juliancwirko/react-npm-boilerplate#6]
Sorry I'm a real beginner ...
I forked the package, then copied the content of the forked package to my own package (using `$ cp -a react-npm-boilerplate/. react-my-custom-package/`), but I guess it's not the right way to go : I cannot commit the new files.

I'm sure I will find how to do this on the internet, but I would have liked it to be part of the Readme. I will update this issue with my findings, and I will try doing a PR on the Readme for the other beginners.

**Comment by aymericbouzy** [comment]
So it seems the best thing is to use the 'import repository' feature from github. If I get validation for this, I can suggest a Readme update.

**Comment by juliancwirko** [comment]
Hi, you can just `git clone` the repo and then remove `.git` folder by `rm -rf .git` then you should be able to initialize your own git repo in it.

**Comment by aymericbouzy** [comment]
Nice! Do you want me to do a PR with the following tip?

**Comment by juliancwirko** [comment]
Sure, you can send PR, thanks :)

**Comment by aymericbouzy** [comment]
Closing in favor of #8
